 {
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.8"
  ],
  "install": [
    "pip install -q -r requirements-dev.txt codecov"
  ],
  "script": [
    "flake8",
    "pytest LibBraga --cov=LibBraga"
  ],
  "after_success": [
    "codecov"]
}